### ISSUE TITLE
Fuzzy matching

### ISSUE THREAD

**Issue by liergou99** [casbin-rs/redis-cache#5]
[https://github.com/casbin/casbin-rs/blob/master/src/cached_enforcer.rs](url)
In lines 67 and 68, redis-cache is used to verify permissions, but it seems that fuzzy matching cannot be used in this way

**Comment by hsluoyz** [comment]
@GopherJ @hackerchai @PsiACE

**Comment by 0x8f701** [comment]
@liergou99 Hi, sorry for my late reply:) always busy with company projects. I didn't fully understand fuzzy matching yet. What you mean by this?

cache key is a hash of your structs/strings, fuzzy matching cache can actually be hard to do, am I understanding correctly what you want?

which makes it difficult is, the cache has no relationship with matcher, so if you use `regexMatch` and everytime the request changes, it'll be difficult to do caching.

@PsiACE @hackerchai do you have any idea?

**Comment by hsluoyz** [comment]
I don't think we support fuzzy in any matching.
